name: fivetoolworkflow
on:
  push:
    branches:
    - master

env:
  FIRST_NAME: Jonathan
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: deploy changes
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www
            cd fivetool
            sudo git pull
            sudo npm run build
            sudo pm2 restart next
          host: ${{ secrets.HOST }}
          user: jonathane
          pass: ${{ secrets.PASS }}