name: fivetoolworkflow
on:
  push:
    branches:
    - master

env:
  FIRST_NAME: Jonathan
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www
            ls -a
            echo "env_var:$FIRST_NAME"
            exit 1
          host: ${{ secrets.HOST }}
          user: jonathane
          pass: ${{ secrets.PASS }}